package claims

const (
	MapKeyExpiresAt = "exp"
	MapKeyIssuedAt  = "iat"
	MapKeyNotBefore = "nbf"
	MapKeyID        = "jti"
	MapKeyIssuer    = "iss"
	MapKeyAudience  = "aud"
	MapKeySubject   = "sub"

	MapKeyGroups            = "groups"
	MapKeyRoles             = "roles"
	MapKeyName              = "name"
	MapKeyFirstName         = "first_name"
	MapKeyLastName          = "last_name"
	MapKeyUsername          = "username"
	MapKeyUserType          = "user_type"
	MapKeyEmail             = "email"
	MapKeyCR                = "cr"
	MapKeyTelephoneNumber   = "telephone_number"
	MapKeyTokenType         = "token_type"
	MapKeyLocationNumber    = "location_number"
	MapKeyLocationType      = "location_type"
	MapKeyDepartmentNumber  = "department_number"
	MapKeyJobDesignation    = "job_designation"
	MapKeyJobTitle          = "job_title"
	MapKeySupervisorOrgCode = "supervisor_org_code"
	MapKeyPreferredLanguage = "preferred_language"
	MapKeyPermissions       = "permissions"
	MapKeyRoleID            = "role_id"
	MapKeyOrganizationID    = "organization_id"
	MapKeyAuthMethod        = "auth_method"
	MapKeySessionID         = "session_id"
	MapKeyDeviceID          = "device_id"
	MapKeyIPAddress         = "ip_address"
	MapKeyLocation          = "location"
	MapKeyScope             = "scope"
	MapKeyClientID          = "client_id"
	MapKeyTimeZone          = "time_zone"
	MapKeyLocale            = "locale"
	MapKeyUserAgent         = "user_agent"
	MapKeyDomain            = "domain"
	MapKeyIsAdmin           = "is_admin"
)
